### ISSUE TITLE
Future Action Args Syntax

### ISSUE THREAD

**Issue by lubelski** [rimunroe/pipeline#13]
## Problem Statement

Packaging action data onto an object provides 'named arugments' but leads to a bunch of boilerplate whenever you want to process an action as you peel the arguments back off.  

Actions that do not pass data (somewhat an anti pattern, but not unreasonable) are ridiculous as they have no payload. 

Trying to use the packager function as syntactic validation is cumbersome and unpredictable.  

## Proposal 1 (Will)

* Action args are simply positional arguments passed straight from the action caller to the action callbacks.  

* createAction (or equivalent) declarations are only required if multiple stores listen to the same action.  

* createAction's function is simply a validation function on the syntactic correctness of the passed arguments. It is therefore basically argTypes to React's propTypes.  

```coffee
app.create.store 'foos', 
  stores: ['bars']
  actions: 
    'foo.create': (fooData) -> 
      @update(fooData.id, fooData)
    'bar.setId': (barId) -> 
      @update(fooId: @stores.bar.getDefaultFooId())

app.create.store 'bars', 
  actions: 
    'bar.setId': (barId) -> @update(barId: barId)

app.create.action 'bar.setId', (barId) -> 
  @isNumber(barId)
```

given these stores and actions: 

```coffee
app.actions.foo.create( {id: 12, baz: 42} ) # fires action

app.actions.foo.create( {id: null, baz: 'bloop'} ) # still fires action, store might blow up.  

app.actions.bar.setBarId(12) # fires action

app.actions.bar.setBarId(null) # doesn't fire action, logs an error
```

**Comment by rimunroe** [comment]
I'm a little confused by the examples, but I strongly agree that actions shouldn't return the payload object, and having a way to validate actions is handy. Trying to trace old code using payload objects is a nightmare, and it feels super clunky to use.

**Comment by rimunroe** [comment]
This is the sort of thing I was thinking of.

```coffee
app.create.action 'newStudent', (id, name, uncheckedArg) ->
  id: _.isNumber(id) and 10000000 < id < 99999999 
  name: _.isString(name) and !_.isEmpty(name)
```

**Comment by lubelski** [comment]
here's my proposal, which requires 1 - 4 methods be available inside of an action validator.  

```coffee
# create an explicit action with no validation 
app.create.action('baz') 

# create an action with a validation function
app.create.action('foo', (name) ->
  @require(_.isString(arg1), "Name must be a string")
  @warn(arg1 is 'butts', "Name shouldn't be 'butts'")
)
```

`require` and `warn` (actual names tbd) would evaluate expressions for their truthiness.  If false, the 2nd argument would be procesed by the logging code in order to construct a useful message.  Multiple failing require messages and warnings would be combined in the logged error message.  

might want 4 total forms: `require_to_be_true`, `require_to_be_false`, `warn_if_true`,  `warn_if_false`, or that might be overkill because `!` is sufficient.  

so given the above code and a started app:   

```
# call an action with invalid arguments
app.actions.foo()
$> View 'bar' called action 'foo' with arguments [] but didn't dispatch because:  
  Name must be a string
```

```
# call an action with arguments that cause a warning.  
app.actions.foo('butts')
$> View 'bar' called action 'foo' with arguments ['butts'] and warned:  
  Name shouldn't be butts.  
```

**Comment by rimunroe** [comment]
This is better. I think it would be silly and outside the scope of the project to provide our own `isNumber` and the like functions, but this is good. I agree that four would be overkill.

"require" is okay, but "warn" doesn't make sense. "require" sounds like, "it is bad if this is not true", but "warn" makes me think "warn if this happens/is true". I think a word that more accurately describes the intent can be found (perhaps along the lines of "prefer"?).

**Comment by rimunroe** [comment]
I'm still a little unsure of whether or not actions should even be able to validate in the first place, or that should be totally up to the store. I think actions validating their arguments is fine, as long as you're not handling validation for the store in the first place.

I don't think it's objectionable to avoid having to have every store perform existence checks on an action's payload, but doing something like in my proposed syntax (checking to make sure that the value is in some narrow range) is probably a sign that you've shifted some logic out of a store and are losing the fire-and-forget benefit of actions with Flux.

**Comment by lubelski** [comment]
totally agree:   

I don't think it's enforceable, but the action's validator should be syntactic, approximately just type checking, but perhaps for loose definitions of 'type'.  i.e.  this value could never be allowed by any store in any context.  

the action callbacks then do symantic reasoning, i.e. meaning of the values.  ex:  this value is not allowed for business reasons, this value is not allowed because of the current state of the system, etc.  

re: naming things. 

require() and suggest() are more semantically correct, but kind of ridiculous.   require is also a node.js term.

**Comment by rimunroe** [comment]
Agreed.

How about "reject" and "warn"? There's still the problem of the implication for the value of the arguments, but they're the best I have at the moment.

**Comment by lubelski** [comment]
Negation is tricksy.  We basically want `reject_if_false` and `warn_if_false` but those sound really boring to type all the time.

**Comment by lubelski** [comment]
should this issue be closed out?
