### ISSUE TITLE
wrap validator functions in a try/catch block

### ISSUE THREAD

**Issue by lubelski** [rimunroe/pipeline#20]
In the case that you have something like: 

```js
app.create.action('actionName', function (foo) {
  this.require(foo, "foo is required")
  this.require(foo.id, "foo ID is required")
});
```
or even
```js
app.create.action('actionName', function (foo) {
  this.require(foo.id, "foo ID is required")
});
```
If `foo` is `undefined`, then the exception should be caught and the action would not be dispatched.

**Comment by rimunroe** [comment]
I think it would be better to just not throw an exception at all, and instead just refuse to dispatch it.

**Comment by lubelski** [comment]
I mean specifically that if foo is supposed to be an object but gets passed as `undefined`, then the property access `foo.id` will itself throw.  

One shouldn't need to write a validator in a way that is 'safe' for all garbage data that could come in.

**Comment by rimunroe** [comment]
Sorry, I don't quite understand what you mean. Could you provide an example?

**Comment by rimunroe** [comment]
The examples you shared are, as far as I know, impossible. You can't stop foo.id from throwing an error in any way that I'm aware of, and I don't know how you'd manage to break out of the validator before you got to that reference.

**Comment by lubelski** [comment]
Exactly.  That's why the validator should be wrapped in a try/catch and an error should be treated as a negative validation.

**Comment by lubelski** [comment]
This is particularly important if the action is in the middle of an enqueued action chain, and I think an uncaught error would kill the whole chain.

**Comment by rimunroe** [comment]
Ah I see what you were getting at. Sorry. It's been a long day. Yes, this is an easy fix too.
